apiVersion: v2
name: freeranue
description: A Helm chart to deploy free-ran-ue
version: 2.0.17
appVersion: latest
icon: https://avatars.githubusercontent.com/u/249334723?s=200&v=4
maintainers:
  - email: alonza.tu@gmail.com
    name: Alonza Tu
