{{- with .Values.gnb }}
{{- if and .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freeranue.fullname" $ }}-{{ .name }}
  labels:
    {{- include "freeranue.labels" $ | nindent 4 }}
    app: {{ $.Values.projectName }}
    component: {{ .name }}
spec:
  selector:
    matchLabels:
      {{- include "freeranue.selectorLabels" $ | nindent 6 }}
      app: {{ $.Values.projectName }}
      component: {{ .name }}
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels:
        {{- include "freeranue.selectorLabels" $ | nindent 8 }}
        app: {{ $.Values.projectName }}
        component: {{ .name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/gnb/gnb-configmap.yaml") $ | sha256sum }}
        {{- include "freeranue.gnbAnnotations" $ | nindent 8 }}
        {{- if and $.Values.global.gnb.multus.enabled (or $.Values.global.gnb.multus.n2network.enabled $.Values.global.gnb.multus.n3network.enabled $.Values.global.gnb.multus.rannetwork.enabled) }}
        k8s.v1.cni.cncf.io/networks: '[
        {{- if $.Values.global.gnb.multus.n2network.enabled }}
            { "name": "{{ $.Values.global.gnb.multus.n2network.name }}-{{ include "freeranue.fullname" $ }}",
              "interface": "n2",
              "ips": [ "{{ .n2if.ipAddress }}/{{ $.Values.global.gnb.multus.n2network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.gnb.multus.n2network.gatewayIP }}" ]
            },
        {{- end }}
        {{- if $.Values.global.gnb.multus.n3network.enabled }}
            { "name": "{{ $.Values.global.gnb.multus.n3network.name }}-{{ include "freeranue.fullname" $ }}",
              "interface": "n3",
              "ips": [ "{{ .n3if.ipAddress }}/{{ $.Values.global.gnb.multus.n3network.cidr }}" ],
              "gateway": [ "{{ $.Values.global.gnb.multus.n3network.gatewayIP }}" ]
            },
        {{- end }}
        {{- if $.Values.global.gnb.multus.rannetwork.enabled }}
            { "name": "{{ $.Values.global.gnb.multus.rannetwork.name }}-{{ include "freeranue.fullname" $ }}",
              "interface": "ran",
              "ips": [ "{{ .ranif.ipAddress }}/{{ $.Values.global.gnb.multus.rannetwork.cidr }}" ],
              "gateway": [ "{{ $.Values.global.gnb.multus.rannetwork.gatewayIP }}" ]
            }
        {{- end }}
            ]'
        {{- end }}
    spec:
      imagePullSecrets:
        {{- toYaml .imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-amf
        {{- with $.Values.initcontainers.sctp_test }}
        image: {{ .image }}:{{ .tag }}
        {{- end }}
      {{- if and (not $.Values.global.gnb.multus.enabled) (not .amf.service.ngap.enabled) }}
        command: ["sh", "-c", "until sctp_test -s -H 0.0.0.0 -P 25000 -h {{ $.Values.global.free5gcReleaseName }}-{{ .amf.n2if.serviceName }} -p {{ .amf.n2if.port }}; do echo waiting for the AMF; sleep 2; done;"]
      {{- else if .amf.service.ngap.enabled }}
        command: ["sh", "-c", "until sctp_test -s -H 0.0.0.0 -P 25000 -h {{ $.Values.global.free5gcReleaseName }}-{{ .amf.n2if.serviceName }} -p {{ .amf.n2if.port }}; do echo waiting for the AMF; sleep 2; done;"]
{{- else }}
        command: ["sh", "-c", "until sctp_test -s -H 0.0.0.0 -P 25000 -h {{ .amf.n2if.ipAddress }} -p {{ .amf.n2if.port }}; do echo waiting for the AMF; sleep 2; done;"]
{{- end }}
      containers:
      - image: {{ .image.name }}:{{ .image.tag | default $.Chart.AppVersion }}
        name: {{ .name }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["/bin/sh", "-c"]
        args: ["{{ .volume.mount }}/wrapper.sh"]
        volumeMounts:
        - mountPath: {{ .volume.mount }}
          name: {{ .volume.name }}
        resources:
            {{- toYaml .resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}

      volumes:
      - name: {{ .volume.name }}
        configMap:
          name: {{ .configmap.name }}
          items:
          - key: gnb.yaml
            path: gnb.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0755
{{- end }}
{{- end }}
